/* apfs-fastindex: generated by cbindgen — do not edit by hand. */

#ifndef APFS_FASTINDEX_H
#define APFS_FASTINDEX_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

/**
 * Depth ceiling for every recursive / iterative tree walk in
 * the crate. Real APFS volumes have OMAP B-trees ≤ 5 levels
 * deep and FS-trees ≤ 8 levels; directory nesting on macOS
 * typically tops out around 10–20. 128 is comfortably above
 * anything legitimate and tight enough that a crafted image
 * with a million-deep chain (or a B-tree cycle pretending to
 * have unbounded depth) hits the cap in milliseconds rather
 * than blowing the stack or hanging the scanner.
 *
 * Walkers that respect this constant: `omap::OmapResolver::lookup`,
 * `omap::walk_node`, `fs_records::walk_fs_node`,
 * `namespace::walk_dir`. `tree::compute_path` is iterative so
 * the depth cap there is informational only.
 */
#define MAX_TREE_DEPTH 128

/**
 * Sentinel returned by `apfs_scan_node_index_for_path` (and
 * future phase-3 hit-test FFIs) when no node matches. Matches
 * `crate::tree::NODE_INVALID == u32::MAX`.
 */
#define APFS_NODE_INVALID UINT32_MAX

/**
 * Sentinel returned by `apfs_layout_hit_test` when no cell
 * covers the point. Matches `crate::tree::NODE_INVALID`
 * (`u32::MAX`).
 */
#define APFS_CELL_INVALID UINT32_MAX

#define CELL_FLAG_DIR (1 << 0)

#define CELL_FLAG_SYMLINK (1 << 1)

#define CELL_FLAG_PADDING_TOP (1 << 2)

/**
 * Sentinel value used by FFI callers for "no such node" /
 * "metric isn't a sum I can give you". `u32::MAX` matches the
 * `APFS_NODE_INVALID` constant in the C header.
 */
#define NODE_INVALID UINT32_MAX

/**
 * Opaque handle holding a `(rows, total_value, any_unclaimed)`
 * snapshot built from a subtree walk. Swift constructs via
 * `apfs_scan_ext_summary_new`, reads rows via `_count` /
 * `_row`, drops via `_free`.
 */
typedef struct ApfsExtSummaryHandle ApfsExtSummaryHandle;

/**
 * Opaque handle representing a treemap layout. Owns both the
 * laid-out cells and the spatial-hash index used for
 * hit-testing. Constructed via `apfs_layout_new`, freed via
 * `apfs_layout_free`. The FFI consumer (Swift) holds the
 * handle for as long as it needs to render or hit-test against
 * the layout.
 */
typedef struct ApfsLayout ApfsLayout;

/**
 * Opaque handle representing a completed fallback scan. Owns
 * the entry buffer, the indexed tree, and supporting strings.
 * Swift sees a `*mut ApfsScan` and must call `apfs_scan_free`
 * when done.
 */
typedef struct ApfsScan ApfsScan;

/**
 * Search result handle returned by `apfs_scan_search_names`.
 * Carries two parallel views into the same search:
 *
 * - `indices`: the **full keep-set** — every matching node
 *   plus every ancestor plus the root, sorted. This is what
 *   a hierarchical tree-list UI needs to render matches in
 *   context.
 * - `matches`: just the nodes whose name matched the query,
 *   sorted. A flat-list "search results" UI uses this to
 *   render matches without forcing an auto-expansion of the
 *   entire ancestor chain (which on a single-letter query
 *   like `"n"` can be 1 M+ nodes, blowing up any
 *   tree-walking renderer).
 *
 * The Swift bridge reads both via dedicated accessors and
 * must call `apfs_search_results_free` exactly once.
 */
typedef struct ApfsSearchResults ApfsSearchResults;

/**
 * C ABI signature for the progress callback the Swift side
 * hands to `apfs_scan_directory_with_progress`. The Rust
 * fallback walker fires events from a dedicated background
 * thread (one event ≈ every 250 ms while the scan runs, plus
 * a final `terminal=true` event when scanning finishes); the
 * callback must be safe to invoke from that thread.
 * Wrapped in `Option<...>` so the C ABI is `void (*)(...)` (a
 * nullable function pointer); cbindgen collapses
 * `Option<extern "C" fn>` to a plain function-pointer typedef
 * when written this way.
 */
typedef void (*ApfsProgressCallback)(uint64_t scanned,
                                     uint64_t skipped,
                                     uint64_t bytes,
                                     uint64_t elapsed_ms,
                                     bool terminal,
                                     void *userdata);

/**
 * Borrowed (ptr, len) pair pointing into a `Tree`-owned UTF-8
 * string. Valid for the lifetime of the enclosing `ApfsScan`.
 * `bytes` is *not* NUL-terminated — Swift constructs `String`
 * via `Data(bytes:count:)` + `String(data:encoding:)`.
 *
 * We don't pay for CString-style NUL-terminated copies for
 * every node because at /-scale that's ~150 MB of duplicate
 * path storage; the borrowed pointer trades one extra Swift
 * API call for zero allocation.
 */
typedef struct ApfsPathRef {
  const uint8_t *bytes;
  uint64_t len;
} ApfsPathRef;

/**
 * Borrowed (ptr, count) slice of child node indices. Lifetime
 * is tied to the enclosing `ApfsScan`; Swift reads as
 * `UnsafeBufferPointer<UInt32>` with no copy.
 */
typedef struct ApfsU32Slice {
  const uint32_t *items;
  uint64_t count;
} ApfsU32Slice;

/**
 * Per-cell record exposed across the FFI. `#[repr(C)]` so Swift
 * can read the struct via `UnsafeBufferPointer<ApfsCell>`
 * without any per-field unwrapping. 32 bytes/cell; ~6.4 MB for
 * a 200 k-cell `/`-scan view.
 */
typedef struct ApfsCell {
  float x0;
  float y0;
  float x1;
  float y1;
  uint32_t depth;
  uint32_t node_index;
  /**
   * Bit 0: is_dir. Bit 1: is_symlink. Bit 2: paddingTop
   * reserved for label (only set on dir cells big enough to
   * host the label strip).
   */
  uint32_t flags;
  /**
   * `0x00RRGGBB`. Pre-computed by the layout pass so the
   * renderer (whether Swift CG or a future Metal pipeline)
   * reads the colour directly without re-running the
   * extension lookup per draw.
   */
  uint32_t fill_rgb;
} ApfsCell;

/**
 * Borrowed view over a laid-out cell array. Valid for the
 * lifetime of the enclosing `ApfsLayout`; Swift reads via
 * `UnsafeBufferPointer<ApfsCell>(start: cells, count: count)`
 * without a copy.
 */
typedef struct ApfsCellSlice {
  const struct ApfsCell *cells;
  uint64_t count;
} ApfsCellSlice;

/**
 * One ext-list row, flattened for the C ABI. Strings are
 * borrowed (lifetime tied to the enclosing
 * `ApfsExtSummaryHandle`); `value_allocated == u64::MAX` is
 * the SR-019 None-collapse sentinel.
 */
typedef struct ApfsExtRow {
  struct ApfsPathRef ext;
  uint64_t value_logical;
  uint64_t value_allocated;
  uint32_t file_count;
  uint32_t _pad;
} ApfsExtRow;

/**
 * Borrowed (path, reason) pair for one walk skip. Both strings
 * are `ApfsPathRef`-shaped: pointer + length, no NUL terminator,
 * owned by `ApfsScan`. UTF-8.
 */
typedef struct ApfsWalkSkipRow {
  struct ApfsPathRef path;
  struct ApfsPathRef reason;
} ApfsWalkSkipRow;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Return a `*const c_char` pointing at the most-recent error
 * message recorded on this thread, or NULL if there is none.
 * Reading clears the slot — the contract is "one read per
 * failure," matching Swift's `Scan.lastError()` semantics.
 *
 * Lifetime: valid until the next call on the same thread that
 * records a new error. Swift wraps with `String(cString:)` and
 * owns the copy from that point on. NUL-terminated UTF-8.
 */
const char *apfs_last_error(void);

/**
 * Return a `*const c_char` pointing at the resolved log-file
 * path (`~/Library/Logs/apfs-fastindex.log` on macOS) the panic
 * hook writes to. NULL if the hook hasn't been installed yet
 * (won't happen after the first scan-related FFI call). The
 * pointer lives for the process lifetime — Swift can cache it.
 */
const char *apfs_log_path(void);

/**
 * Returns a constant integer the Swift side can assert on to
 * confirm the FFI bridge is wired correctly. The number is the
 * MWP-trivia answer; if it changes, something has gone wrong
 * with name mangling or the static-lib search path.
 */
int apfs_hello(void);

/**
 * Returns the apfs-fastindex crate version as a NUL-terminated
 * UTF-8 string (static, so the pointer is valid for the
 * lifetime of the process — Swift must not free it). The
 * version is baked at compile time from `Cargo.toml`.
 */
const char *apfs_version(void);

/**
 * Scan a directory and return an owning `ApfsScan*`. `threads`
 * of 0 uses the default (min of physical-cpu and 4 per EX-25).
 * `cross_mounts` toggles whether the walker descends into
 * directories on a different device than the root.
 *
 * Returns `NULL` on:
 *   - `path` is NULL
 *   - `path` is not valid UTF-8
 *   - the scan returns an error (bad source, permission denial
 *     at root, etc.)
 */
struct ApfsScan *apfs_scan_directory(const char *path, uint32_t threads, bool cross_mounts);

/**
 * Like `apfs_scan_directory` but with a live progress callback.
 * `progress_fn` is invoked from a background thread roughly
 * every 250 ms during the scan; the final event has
 * `terminal == true`. Passing NULL for `progress_fn` is
 * equivalent to calling `apfs_scan_directory` (no progress
 * events).
 */
struct ApfsScan *apfs_scan_directory_with_progress(const char *path,
                                                   uint32_t threads,
                                                   bool cross_mounts,
                                                   ApfsProgressCallback progress_fn,
                                                   void *userdata);

/**
 * True iff `path` resolves to a filesystem mounted as a
 * snapshot (statfs.f_flags & MNT_SNAPSHOT). Returns 0 for any
 * error (path NULL, not UTF-8, statfs failed) so the caller
 * treats a non-snapshot as the safe default.
 *
 * EX-29 follow-up: the Swift bridge can't reach Darwin's
 * `statfs(_:_:)` function unambiguously through the overlay
 * (name collision with `struct statfs`). Calling out to this
 * FFI is the workaround.
 */
int32_t apfs_is_snapshot_path(const char *path);

/**
 * Load an ApfsScan from a previously-emitted msgpack file.
 *
 * The privileged-subprocess "Scan as Administrator…" flow
 * spawns `apfs-fastindex-scan --format msgpack ...` via
 * osascript with administrator privileges. The subprocess
 * writes its `FallbackScanOutput` as a msgpack blob to a temp
 * file the parent app picks; on subprocess exit, the parent
 * calls this FFI to rehydrate an `ApfsScan` from that file —
 * identical to the in-process scan handle the Swift renderer
 * normally reads.
 *
 * Returns `NULL` on:
 * - `path` is NULL or not valid UTF-8
 * - the file can't be opened or read
 * - the msgpack blob fails to decode as `FallbackScanOutput`
 *
 * On any of those, the caller can read `apfs_last_error` for a
 * human-readable diagnostic.
 */
struct ApfsScan *apfs_scan_from_msgpack_file(const char *path);

/**
 * Drop a scan handle. Idempotent on NULL.
 */
void apfs_scan_free(struct ApfsScan *scan);

/**
 * Number of `NamespaceEntry` rows in the scan.
 */
uint64_t apfs_scan_entry_count(const struct ApfsScan *scan);

/**
 * Sum of `entry.logical_size` across the whole scan. Reads off
 * the tree root's pre-computed aggregate.
 */
uint64_t apfs_scan_logical_total(const struct ApfsScan *scan);

/**
 * Sum of `entry.allocated_size` across the whole scan, or
 * `APFS_ALLOCATED_TOTAL_UNCLAIMED` (`u64::MAX`) when *any* row
 * had `allocated_size = None` (SR-019 None-collapse). Reads off
 * the tree root's pre-computed aggregate.
 */
uint64_t apfs_scan_allocated_total(const struct ApfsScan *scan);

/**
 * Sum of `entry.real_size` (EX-27 clone-deduplicated allocated
 * bytes) across the whole scan, or `APFS_REAL_TOTAL_UNCLAIMED`
 * (`u64::MAX`) when *any* row had `real_size = None`. Reads off
 * the tree root's pre-computed aggregate.
 */
uint64_t apfs_scan_real_total(const struct ApfsScan *scan);

/**
 * `true` iff at least one entry in the scan has
 * `real_size = Some(_)`. The Swift UI toggles the "Real" metric
 * chip off when this is false. Fallback mode populates this same
 * as `allocated_size` (no refcount info from POSIX), so on a
 * well-formed scan both are typically `true`.
 */
bool apfs_scan_real_available(const struct ApfsScan *scan);

/**
 * Total number of nodes in the tree (root + every directory +
 * every leaf). Differs from `apfs_scan_entry_count` because the
 * tree also has synthesized intermediate directories.
 */
uint32_t apfs_scan_node_count(const struct ApfsScan *scan);

/**
 * Case-insensitive substring search across every node's
 * display name. Returns a handle wrapping the **full
 * keep-set**: every matching node index plus every ancestor
 * of every match, plus the root. This is the set the UI
 * renders as the visible tree under an active search;
 * pushing the ancestor-walk into Rust avoids a per-ancestor
 * FFI call from Swift (which on a pathological match-everything
 * query would have been millions of FFI hits).
 *
 * Architecture (EX-33 follow-up):
 *
 * 1. The tree carries a **flat lowercased-name buffer**
 *    (`tree.names_lower_buf: Vec<u8>` + offsets), built once
 *    at scan time. Scanning every name reads sequentially
 *    from one contiguous allocation; the CPU prefetcher
 *    streams through it. (The prior `Vec<String>` shape
 *    forced a heap-pointer chase per name, defeating
 *    prefetch — ~10× slower on 1.5 M-node trees.)
 *
 * 2. The query is lowercased once and wrapped in a
 *    `memchr::memmem::Finder`. The Finder amortises
 *    needle-preprocessing across every haystack call;
 *    `str::contains` builds the searcher state per call,
 *    which is wasted work when we have 1.5 M haystacks
 *    to scan with the same needle.
 *
 * 3. For each name whose bytes contain the lowercased
 *    needle, walk the parent chain (`tree.nodes[i].parent:
 *    Option<u32>`) and insert every ancestor into an
 *    `FxHashSet`. Early-out: when `insert` returns false
 *    (node already in), the rest of that chain is too —
 *    total ancestor work is O(unique kept nodes), not
 *    O(matches × depth).
 *
 * EX-33 numbers on a 1.56 M-entry `/Users/kai` scan: search
 * latency dropped from 30-55 ms (median) under the
 * Vec<String> + str::contains shape to ~3-6 ms. That's
 * approaching the memory-bandwidth floor (~50 MB of name
 * bytes / ~20 GB/s ≈ 2.5 ms).
 *
 * Returns `NULL` on:
 * - `scan` or `query` NULL
 * - `query` not valid UTF-8
 * - `query` empty (caller treats "" as "no filter" and skips
 *   this call entirely; returning a sentinel handle would be
 *   wasteful)
 *
 * The result handle owns its indices buffer; Swift must call
 * `apfs_search_results_free` when done.
 */
struct ApfsSearchResults *apfs_scan_search_names(const struct ApfsScan *scan, const char *query);

/**
 * Number of matching node indices in `results`. `0` on NULL.
 */
uintptr_t apfs_search_results_count(const struct ApfsSearchResults *results);

/**
 * Pointer to the matching-node-indices buffer. Length given
 * by `apfs_search_results_count`. Buffer is valid until
 * `apfs_search_results_free` is called.
 */
const uint32_t *apfs_search_results_indices(const struct ApfsSearchResults *results);

/**
 * Drop the search-results handle. Idempotent on NULL.
 */
void apfs_search_results_free(struct ApfsSearchResults *results);

/**
 * Number of nodes whose name matched the query (i.e. the
 * "real" matches, not the inflated keep-set). `0` on NULL.
 */
uintptr_t apfs_search_results_match_count(const struct ApfsSearchResults *results);

/**
 * Pointer to the matches buffer (`u32` per entry, length
 * from `apfs_search_results_match_count`). Sorted in tree
 * (node-index) order. Valid until `apfs_search_results_free`.
 */
const uint32_t *apfs_search_results_match_indices(const struct ApfsSearchResults *results);

/**
 * Look up a node by its absolute logical path. The empty string
 * (and `"/"`) maps to the synthesised root (index 0). Returns
 * `APFS_NODE_INVALID` if no such node exists.
 */
uint32_t apfs_scan_node_index_for_path(const struct ApfsScan *scan, const char *path);

/**
 * Number of immediate children of the given node.
 * `apfs_scan_node_child_count(s, root) == top-level dir/file
 * count`. Returns 0 for invalid indices.
 */
uint32_t apfs_scan_node_child_count(const struct ApfsScan *scan, uint32_t idx);

/**
 * Per-node aggregate read by Swift's status bar. Pre-computed
 * post-order at `Tree::build` time; constant-time lookup.
 */
uint64_t apfs_scan_node_value_logical(const struct ApfsScan *scan, uint32_t idx);

/**
 * `value_allocated` for the node, or
 * `APFS_ALLOCATED_TOTAL_UNCLAIMED` (`u64::MAX`) when SR-019
 * None-collapse fired anywhere in this subtree.
 */
uint64_t apfs_scan_node_value_allocated(const struct ApfsScan *scan, uint32_t idx);

/**
 * Item count for the node — number of non-directory descendants.
 * `apfs_scan_node_item_count(s, root) == files+symlinks total`.
 */
uint64_t apfs_scan_node_item_count(const struct ApfsScan *scan, uint32_t idx);

/**
 * Borrow the node's absolute logical path. Returns a null
 * pointer + zero length for invalid indices.
 *
 * The path isn't stored on `TreeNode` (round 4 of the perf
 * pass dropped it — saved 16 B per node). We compute on demand
 * via parent-walk and cache the materialised `Box<str>` in
 * `ApfsScan.path_cache`. Pointer lifetime matches the scan
 * handle: the cache owns the bytes until `apfs_scan_free`.
 */
struct ApfsPathRef apfs_scan_node_path(const struct ApfsScan *scan, uint32_t idx);

/**
 * Borrow the node's last path component (display name). Like
 * `apfs_scan_node_path` but returns just the leaf basename.
 */
struct ApfsPathRef apfs_scan_node_name(const struct ApfsScan *scan, uint32_t idx);

/**
 * Parent index for `idx`, or `APFS_NODE_INVALID` for the root
 * (no parent) or an invalid `idx`. Used by Swift's breadcrumb
 * construction (walk parent chain from `currentNode` to root).
 */
uint32_t apfs_scan_node_parent(const struct ApfsScan *scan, uint32_t idx);

/**
 * Returns the node's `EntryKind` as a u32 discriminant:
 *   0 = dir, 1 = file, 2 = symlink, 3 = other, 0xff = invalid
 * Swift maps back to a `Scan.NodeKind` enum.
 */
uint32_t apfs_scan_node_kind(const struct ApfsScan *scan, uint32_t idx);

/**
 * Borrow the slice of immediate-child node indices for `idx`.
 * Returns an empty slice for invalid indices or leaves.
 */
struct ApfsU32Slice apfs_scan_node_children(const struct ApfsScan *scan, uint32_t idx);

/**
 * Lay out the subtree rooted at `node_idx` inside a viewport of
 * (`width`, `height`) CSS pixels. `max_depth = 0` is the
 * no-truncation sentinel (render every descendant; cull only by
 * `MIN_PIXEL_AREA = 1`).
 *
 * `metric`:
 *   - `0` → logical
 *   - `1` → allocated
 *
 * The returned handle owns both the cell array and the
 * `HitGrid` for hit-testing. Always pair with
 * `apfs_layout_free`.
 */
struct ApfsLayout *apfs_layout_new(const struct ApfsScan *scan,
                                   uint32_t node_idx,
                                   uint32_t max_depth,
                                   uint32_t metric,
                                   float width,
                                   float height);

/**
 * Reclaim a layout previously returned by `apfs_layout_new`.
 * Idempotent on NULL.
 */
void apfs_layout_free(struct ApfsLayout *layout);

/**
 * Borrow the laid-out cells. Pointer lifetime is tied to the
 * enclosing `ApfsLayout`; Swift must not retain the slice past
 * the layout handle's lifetime.
 */
struct ApfsCellSlice apfs_layout_cells(const struct ApfsLayout *layout);

/**
 * Number of cells in the layout. Convenience accessor — the
 * same value is on `ApfsCellSlice.count`.
 */
uint64_t apfs_layout_cell_count(const struct ApfsLayout *layout);

/**
 * Find the deepest cell containing `(x, y)`. Returns
 * `APFS_CELL_INVALID` (`u32::MAX`) if no cell does or
 * `(x, y)` is outside the laid-out rect. Sub-millisecond on a
 * /-class scan thanks to the 64×64 spatial hash; OK to call
 * every mousemove.
 */
uint32_t apfs_layout_hit_test(const struct ApfsLayout *layout, float x, float y);

/**
 * Construct the ext-list summary for the subtree rooted at
 * `node_idx`. `metric == 1` sorts by allocated; anything else
 * sorts by logical. Returns NULL on invalid scan / idx.
 */
struct ApfsExtSummaryHandle *apfs_scan_ext_summary_new(const struct ApfsScan *scan,
                                                       uint32_t node_idx,
                                                       uint32_t metric);

/**
 * Drop the summary handle. Idempotent on NULL.
 */
void apfs_scan_ext_summary_free(struct ApfsExtSummaryHandle *handle);

uint32_t apfs_scan_ext_summary_count(const struct ApfsExtSummaryHandle *handle);

/**
 * Sum of the active-metric values across all rows. Used by
 * Swift for the per-row percent column. Returns 0 on
 * invalid handle.
 */
uint64_t apfs_scan_ext_summary_total(const struct ApfsExtSummaryHandle *handle);

/**
 * True iff at least one contributing file's `allocated_size`
 * was None (SR-019 None-collapse). The Swift panel uses this
 * to caption the header subtitle.
 */
bool apfs_scan_ext_summary_any_unclaimed(const struct ApfsExtSummaryHandle *handle);

/**
 * Fetch row `n`. Returns a zero-filled row if `n` is out of
 * range or the handle is NULL.
 */
struct ApfsExtRow apfs_scan_ext_summary_row(const struct ApfsExtSummaryHandle *handle, uint32_t n);

/**
 * `true` iff at least one entry has `allocated_size = Some(_)`.
 * The Swift UI uses this to gate the "Allocated" metric chip.
 */
bool apfs_scan_allocated_available(const struct ApfsScan *scan);

/**
 * `correctness_claim` (UTF-8, NUL-terminated). The returned
 * pointer is owned by `scan` and is valid until
 * `apfs_scan_free(scan)`. Swift must not free it.
 */
const char *apfs_scan_correctness_claim(const struct ApfsScan *scan);

/**
 * `SourceDescriptor.source_kind` (e.g. `"mounted_directory"`,
 * `"dmg_image"`). UTF-8, NUL-terminated; owned by `scan`.
 */
const char *apfs_scan_source_kind(const struct ApfsScan *scan);

/**
 * `SourceDescriptor.requested_path`, the absolute path the user
 * asked us to scan. UTF-8, NUL-terminated; owned by `scan`.
 */
const char *apfs_scan_source_requested_path(const struct ApfsScan *scan);

/**
 * Number of `walk_skip` rows recorded during the scan. 0 when
 * the scan completed cleanly.
 */
uint32_t apfs_scan_walk_skip_count(const struct ApfsScan *scan);

/**
 * Fetch walk-skip row `n`. Returns an all-NULL row for out-of-
 * range indices or a NULL handle.
 */
struct ApfsWalkSkipRow apfs_scan_walk_skip_row(const struct ApfsScan *scan, uint32_t n);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* APFS_FASTINDEX_H */
