//! C ABI surface consumed by the native renderer's Swift code.
//!
//! Everything that crosses this boundary is `#[no_mangle] extern
//! "C"`. The header is generated by cbindgen at build time
//! (`build.rs`), then `build-native.sh` copies it into the
//! SwiftPM `CApfsFastindex` shim target.
//!
//! Design notes:
//!
//! - Strings cross the boundary as `*const c_char` (UTF-8,
//!   NUL-terminated). Swift wraps with `String(cString:)`. The
//!   Rust side owns each string for the lifetime of the
//!   enclosing handle (e.g. an `ApfsScan*` keeps all its path
//!   strings alive until `apfs_scan_free` runs).
//! - Bulk buffers (entry lists, cell lists, tree-list rows) are
//!   exposed as `(*const Item, usize)` pairs so Swift reads
//!   them as `UnsafeBufferPointer` without per-item FFI traffic.
//! - Every "new" function has a matching `_free` that the Swift
//!   side calls in `deinit`. Ownership rule: the caller of `new`
//!   is responsible for `_free`.
//! - Optional integer fields use the sentinel `u64::MAX` (or
//!   `i64::MIN` where applicable) for `None`. Cleaner than a
//!   parallel "has-this-field" bool from a FFI standpoint;
//!   Swift maps the sentinel back to `nil` on the wrapper side.

use std::ffi::{CStr, CString};
use std::os::raw::{c_char, c_int};
use std::ptr;

use crate::{fallback_scan_path_with_options, FallbackOptions};

// ─────────────────────────────────────────────────────────────
// Phase 1 sanity-check surface
// ─────────────────────────────────────────────────────────────

/// Returns a constant integer the Swift side can assert on to
/// confirm the FFI bridge is wired correctly. The number is the
/// MWP-trivia answer; if it changes, something has gone wrong
/// with name mangling or the static-lib search path.
#[no_mangle]
pub extern "C" fn apfs_hello() -> c_int {
    42
}

/// Returns the apfs-fastindex crate version as a NUL-terminated
/// UTF-8 string (static, so the pointer is valid for the
/// lifetime of the process — Swift must not free it). The
/// version is baked at compile time from `Cargo.toml`.
#[no_mangle]
pub extern "C" fn apfs_version() -> *const c_char {
    // `concat!` produces a static `&'static str`; appending a
    // trailing `\0` byte and exposing the data pointer is the
    // idiomatic way to hand a C string out of Rust without an
    // allocation.
    static VERSION: &str = concat!(env!("CARGO_PKG_VERSION"), "\0");
    VERSION.as_ptr() as *const c_char
}

// ─────────────────────────────────────────────────────────────
// Phase 2: scan FFI
// ─────────────────────────────────────────────────────────────

/// Opaque handle representing a completed fallback scan. Owns
/// the entry buffer + supporting strings. Swift sees a
/// `*mut ApfsScan` and must call `apfs_scan_free` when done.
pub struct ApfsScan {
    pub(crate) output: crate::FallbackScanOutput,
    // CStrings keep the NUL-terminated bytes alive for the
    // lifetime of the scan. Pointers handed to Swift point
    // into these — Swift must not free them; they go away
    // when `apfs_scan_free` drops the box.
    correctness_claim: CString,
    source_kind: CString,
    source_requested_path: CString,
    // Cached totals so Swift's status-bar updates don't
    // re-walk the entry buffer.
    logical_total: u64,
    /// Cached allocated-size total, with the `Option<u64>` shape
    /// preserved (`None` = SR-019 / EX-22 None-collapse: at
    /// least one row's allocated_size is unclaimed).
    allocated_total: Option<u64>,
    /// True iff *any* entry has `allocated_size = Some(_)`.
    /// The Swift UI toggles the "Allocated" metric chip off
    /// when this is false.
    allocated_available: bool,
}

/// Sentinel for "no allocated total" (SR-019 None-collapse).
/// Pre-baked at the C-ABI boundary because Option<u64> doesn't
/// cross unmodified.
const APFS_ALLOCATED_TOTAL_UNCLAIMED: u64 = u64::MAX;

/// Scan a directory and return an owning `ApfsScan*`. `threads`
/// of 0 uses the default (min of physical-cpu and 4 per EX-25).
/// `cross_mounts` toggles whether the walker descends into
/// directories on a different device than the root.
///
/// Returns `NULL` on:
///   - `path` is NULL
///   - `path` is not valid UTF-8
///   - the scan returns an error (bad source, permission denial
///     at root, etc.)
#[no_mangle]
pub extern "C" fn apfs_scan_directory(
    path: *const c_char,
    threads: u32,
    cross_mounts: bool,
) -> *mut ApfsScan {
    if path.is_null() {
        return ptr::null_mut();
    }
    let cstr = unsafe { CStr::from_ptr(path) };
    let path_str = match cstr.to_str() {
        Ok(s) => s,
        Err(_) => return ptr::null_mut(),
    };
    let options = FallbackOptions {
        cross_mounts,
        progress: None,
        threads: if threads == 0 { 4 } else { threads as usize },
    };
    let output = match fallback_scan_path_with_options(path_str, options) {
        Ok(o) => o,
        Err(_) => return ptr::null_mut(),
    };

    // Walk entries once to compute cached totals + the
    // allocated-available flag.
    let mut logical: u64 = 0;
    let mut allocated: Option<u64> = Some(0);
    let mut allocated_available = false;
    for entry in &output.parser_output.entries {
        logical = logical.saturating_add(entry.logical_size);
        if entry.allocated_size.is_some() {
            allocated_available = true;
        }
        if let Some(a) = allocated {
            allocated = match entry.allocated_size {
                Some(n) => Some(a.saturating_add(n)),
                None => None,
            };
        }
    }

    let claim_c = CString::new(output.correctness_claim.clone())
        .unwrap_or_else(|_| CString::new("").unwrap());
    let source_kind_c = CString::new(output.parser_output.source.source_kind.clone())
        .unwrap_or_else(|_| CString::new("").unwrap());
    let source_requested_path_c = CString::new(
        output.parser_output.source.requested_path.to_string_lossy().into_owned(),
    )
    .unwrap_or_else(|_| CString::new("").unwrap());

    let scan = Box::new(ApfsScan {
        output,
        correctness_claim: claim_c,
        source_kind: source_kind_c,
        source_requested_path: source_requested_path_c,
        logical_total: logical,
        allocated_total: allocated,
        allocated_available,
    });
    Box::into_raw(scan)
}

/// Drop a scan handle. Idempotent on NULL.
#[no_mangle]
pub extern "C" fn apfs_scan_free(scan: *mut ApfsScan) {
    if scan.is_null() {
        return;
    }
    // SAFETY: caller must have obtained `scan` from
    // `apfs_scan_directory` and not yet freed it.
    unsafe {
        drop(Box::from_raw(scan));
    }
}

/// Number of `NamespaceEntry` rows in the scan.
#[no_mangle]
pub extern "C" fn apfs_scan_entry_count(scan: *const ApfsScan) -> u64 {
    let Some(s) = (unsafe { scan.as_ref() }) else { return 0; };
    s.output.parser_output.entries.len() as u64
}

/// Sum of `entry.logical_size` across the whole scan. Cached at
/// scan-construction time; this is a single field read.
#[no_mangle]
pub extern "C" fn apfs_scan_logical_total(scan: *const ApfsScan) -> u64 {
    let Some(s) = (unsafe { scan.as_ref() }) else { return 0; };
    s.logical_total
}

/// Sum of `entry.allocated_size` across the whole scan, or
/// `APFS_ALLOCATED_TOTAL_UNCLAIMED` (`u64::MAX`) when *any* row
/// had `allocated_size = None` (SR-019 None-collapse). Swift
/// maps the sentinel back to `nil`.
#[no_mangle]
pub extern "C" fn apfs_scan_allocated_total(scan: *const ApfsScan) -> u64 {
    let Some(s) = (unsafe { scan.as_ref() }) else { return APFS_ALLOCATED_TOTAL_UNCLAIMED; };
    s.allocated_total.unwrap_or(APFS_ALLOCATED_TOTAL_UNCLAIMED)
}

/// `true` iff at least one entry has `allocated_size = Some(_)`.
/// The Swift UI uses this to gate the "Allocated" metric chip.
#[no_mangle]
pub extern "C" fn apfs_scan_allocated_available(scan: *const ApfsScan) -> bool {
    let Some(s) = (unsafe { scan.as_ref() }) else { return false; };
    s.allocated_available
}

/// `correctness_claim` (UTF-8, NUL-terminated). The returned
/// pointer is owned by `scan` and is valid until
/// `apfs_scan_free(scan)`. Swift must not free it.
#[no_mangle]
pub extern "C" fn apfs_scan_correctness_claim(scan: *const ApfsScan) -> *const c_char {
    let Some(s) = (unsafe { scan.as_ref() }) else { return ptr::null(); };
    s.correctness_claim.as_ptr()
}

/// `SourceDescriptor.source_kind` (e.g. `"mounted_directory"`,
/// `"dmg_image"`). UTF-8, NUL-terminated; owned by `scan`.
#[no_mangle]
pub extern "C" fn apfs_scan_source_kind(scan: *const ApfsScan) -> *const c_char {
    let Some(s) = (unsafe { scan.as_ref() }) else { return ptr::null(); };
    s.source_kind.as_ptr()
}

/// `SourceDescriptor.requested_path`, the absolute path the user
/// asked us to scan. UTF-8, NUL-terminated; owned by `scan`.
#[no_mangle]
pub extern "C" fn apfs_scan_source_requested_path(scan: *const ApfsScan) -> *const c_char {
    let Some(s) = (unsafe { scan.as_ref() }) else { return ptr::null(); };
    s.source_requested_path.as_ptr()
}
