//! C ABI surface consumed by the native renderer's Swift code.
//!
//! Everything that crosses this boundary is `#[no_mangle] extern
//! "C"`. The header is generated by cbindgen at build time
//! (`build.rs`), then `make-release.sh` copies it into the
//! SwiftPM `CApfsFastindex` shim target.
//!
//! Design notes:
//!
//! - Strings cross the boundary as `*const c_char` (UTF-8,
//!   NUL-terminated). Swift wraps with `String(cString:)`. The
//!   Rust side owns each string for the lifetime of the
//!   enclosing handle (e.g. an `ApfsScan*` keeps all its path
//!   strings alive until `apfs_scan_free` runs).
//! - Bulk buffers (entry lists, cell lists, tree-list rows) are
//!   exposed as `(*const Item, usize)` pairs so Swift reads
//!   them as `UnsafeBufferPointer` without per-item FFI traffic.
//! - Every "new" function has a matching `_free` that the Swift
//!   side calls in `deinit`. Ownership rule: the caller of `new`
//!   is responsible for `_free`.
//! - Optional integer fields use the sentinel `u64::MAX` (or
//!   `i64::MIN` where applicable) for `None`. Cleaner than a
//!   parallel "has-this-field" bool from a FFI standpoint;
//!   Swift maps the sentinel back to `nil` on the wrapper side.

use std::collections::HashMap;
use std::ffi::{CStr, CString};
use std::os::raw::{c_char, c_int};
use std::ptr;

use crate::ext_summary::ExtSummary;
use crate::render::{render_cells, ApfsCell, ApfsLayout, HitGrid, Metric};
use crate::tree::{Tree, NODE_INVALID};
use crate::{fallback_scan_path_with_options, FallbackOptions, ProgressEvent};

/// Run `f` inside a `catch_unwind` barrier and return `sentinel`
/// if a Rust panic is caught. Every `#[no_mangle] extern "C" fn`
/// in this module wraps its body in this helper. Without it, a
/// panic in Rust code (parser asserts, index-out-of-range, etc.)
/// would unwind across the C ABI into the Swift caller, which is
/// undefined behavior — the SwiftUI app gets memory corruption
/// or an abort, not a graceful error path.
///
/// `panic = "abort"` is set workspace-wide in the release profile
/// as a defence-in-depth backstop, so this wrapper is the
/// guaranteed source-level barrier on debug builds (where
/// unwinding is on) and a no-op on release builds (which abort
/// before unwinding ever reaches us). Either way the C caller
/// never sees a partial-unwind state.
///
/// `AssertUnwindSafe` is required because most of our FFI bodies
/// capture references / `*mut` pointers that don't implement
/// `UnwindSafe` automatically; the bodies are short and don't
/// leave shared state inconsistent if they panic.
#[inline]
fn ffi_guard<R>(sentinel: R, f: impl FnOnce() -> R) -> R {
    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(f)) {
        Ok(r) => r,
        Err(_) => sentinel,
    }
}

// ─────────────────────────────────────────────────────────────
// Phase 1 sanity-check surface
// ─────────────────────────────────────────────────────────────

/// Returns a constant integer the Swift side can assert on to
/// confirm the FFI bridge is wired correctly. The number is the
/// MWP-trivia answer; if it changes, something has gone wrong
/// with name mangling or the static-lib search path.
#[no_mangle]
pub extern "C" fn apfs_hello() -> c_int {
    ffi_guard(0, move || 42)
}

/// Returns the apfs-fastindex crate version as a NUL-terminated
/// UTF-8 string (static, so the pointer is valid for the
/// lifetime of the process — Swift must not free it). The
/// version is baked at compile time from `Cargo.toml`.
#[no_mangle]
pub extern "C" fn apfs_version() -> *const c_char {
    ffi_guard(ptr::null(), move || {
        // `concat!` produces a static `&'static str`; appending a
        // trailing `\0` byte and exposing the data pointer is the
        // idiomatic way to hand a C string out of Rust without an
        // allocation.
        static VERSION: &str = concat!(env!("CARGO_PKG_VERSION"), "\0");
        VERSION.as_ptr() as *const c_char
    })
}

// ─────────────────────────────────────────────────────────────
// Phase 2: scan FFI
// ─────────────────────────────────────────────────────────────

/// Opaque handle representing a completed fallback scan. Owns
/// the entry buffer, the indexed tree, and supporting strings.
/// Swift sees a `*mut ApfsScan` and must call `apfs_scan_free`
/// when done.
pub struct ApfsScan {
    pub(crate) output: crate::FallbackScanOutput,
    /// Indexed tree over `output.parser_output.entries`.
    /// Phase 3 builds this at scan time so the renderer can
    /// query it by path without re-scanning the entry list.
    pub(crate) tree: Tree,
    /// Lazy cache for `apfs_scan_node_path`. `TreeNode` itself no
    /// longer stores the materialised path (round 4 of the perf
    /// pass — saved 16 B per node by computing on demand); the
    /// FFI populates this cache on first query and then returns
    /// the borrowed slice on every subsequent call for the same
    /// `idx`. `Mutex` rather than `RefCell` so the FFI is safe
    /// to call from multiple Swift threads (the Swift bridge
    /// doesn't actually do that today, but the C signature
    /// doesn't gate against it).
    path_cache: std::sync::Mutex<HashMap<u32, Box<str>>>,
    // CStrings keep the NUL-terminated bytes alive for the
    // lifetime of the scan. Pointers handed to Swift point
    // into these — Swift must not free them; they go away
    // when `apfs_scan_free` drops the box.
    correctness_claim: CString,
    source_kind: CString,
    source_requested_path: CString,
    /// True iff *any* entry has `allocated_size = Some(_)`.
    /// The Swift UI toggles the "Allocated" metric chip off
    /// when this is false.
    allocated_available: bool,
}

/// Sentinel for "no allocated total" (SR-019 None-collapse).
/// Pre-baked at the C-ABI boundary because Option<u64> doesn't
/// cross unmodified.
const APFS_ALLOCATED_TOTAL_UNCLAIMED: u64 = u64::MAX;

/// Scan a directory and return an owning `ApfsScan*`. `threads`
/// of 0 uses the default (min of physical-cpu and 4 per EX-25).
/// `cross_mounts` toggles whether the walker descends into
/// directories on a different device than the root.
///
/// Returns `NULL` on:
///   - `path` is NULL
///   - `path` is not valid UTF-8
///   - the scan returns an error (bad source, permission denial
///     at root, etc.)
#[no_mangle]
pub extern "C" fn apfs_scan_directory(
    path: *const c_char,
    threads: u32,
    cross_mounts: bool,
) -> *mut ApfsScan {
    ffi_guard(ptr::null_mut(), move || {
        // Thin wrapper: the no-progress path is just the
        // with-progress path called with a NULL callback. Keeps the
        // post-scan finalize logic in one place
        // (`finalize_scan_handle`).
        apfs_scan_directory_with_progress(path, threads, cross_mounts, None, ptr::null_mut())
    })
}

/// C ABI signature for the progress callback the Swift side
/// hands to `apfs_scan_directory_with_progress`. The Rust
/// fallback walker fires events from a dedicated background
/// thread (one event ≈ every 250 ms while the scan runs, plus
/// a final `terminal=true` event when scanning finishes); the
/// callback must be safe to invoke from that thread.
/// Wrapped in `Option<...>` so the C ABI is `void (*)(...)` (a
/// nullable function pointer); cbindgen collapses
/// `Option<extern "C" fn>` to a plain function-pointer typedef
/// when written this way.
// `bytes` is the cumulative `logical_size` sum for entries
// scanned so far — drives a determinate progress bar (numerator)
// against a volume-capacity denominator on the Swift side.
pub type ApfsProgressCallback = Option<
    extern "C" fn(
        scanned: u64,
        skipped: u64,
        bytes: u64,
        elapsed_ms: u64,
        terminal: bool,
        userdata: *mut std::os::raw::c_void,
    ),
>;

/// Newtype around the raw userdata pointer so we can opt into
/// `Send` for the closure that moves it into the parallel
/// walker. Swift caller is responsible for actual thread
/// safety — typically the userdata is an `Unmanaged.toOpaque()`
/// reference to a Swift box.
struct ProgressUserdata(*mut std::os::raw::c_void);
unsafe impl Send for ProgressUserdata {}

/// Like `apfs_scan_directory` but with a live progress callback.
/// `progress_fn` is invoked from a background thread roughly
/// every 250 ms during the scan; the final event has
/// `terminal == true`. Passing NULL for `progress_fn` is
/// equivalent to calling `apfs_scan_directory` (no progress
/// events).
#[no_mangle]
pub extern "C" fn apfs_scan_directory_with_progress(
    path: *const c_char,
    threads: u32,
    cross_mounts: bool,
    progress_fn: ApfsProgressCallback,
    userdata: *mut std::os::raw::c_void,
) -> *mut ApfsScan {
    ffi_guard(ptr::null_mut(), move || {
        if path.is_null() {
            return ptr::null_mut();
        }
        let cstr = unsafe { CStr::from_ptr(path) };
        let path_str = match cstr.to_str() {
            Ok(s) => s,
            Err(_) => return ptr::null_mut(),
        };
        let user = ProgressUserdata(userdata);
        let mut progress_closure = move |event: ProgressEvent| {
            // Rebind to a reference so disjoint-captures captures the
            // whole `ProgressUserdata` (which is `Send` via the unsafe
            // impl above) rather than projecting `user.0`, which would
            // be a bare `*mut c_void` and not `Send`.
            let user = &user;
            if let Some(cb) = progress_fn {
                cb(
                    event.scanned,
                    event.skipped,
                    event.bytes,
                    event.elapsed.as_millis() as u64,
                    event.terminal,
                    user.0,
                );
            }
        };
        let progress_ref: Option<&mut (dyn FnMut(ProgressEvent) + Send)> = if progress_fn.is_some()
        {
            Some(&mut progress_closure)
        } else {
            None
        };
        let options = FallbackOptions {
            cross_mounts,
            progress: progress_ref,
            threads: if threads == 0 { 4 } else { threads as usize },
            // FFI consumers (the SwiftUI app) read subtree totals
            // from the indexed `Tree`, not from the legacy
            // `aggregates` Vec — skip the ~90 ms aggregate pass.
            skip_aggregates: true,
        };
        let output = match fallback_scan_path_with_options(path_str, options) {
            Ok(o) => o,
            Err(_) => return ptr::null_mut(),
        };
        finalize_scan_handle(output)
    })
}

/// Shared post-scan handle construction. Called by both the
/// progress and no-progress entry points. Builds the indexed
/// tree, caches the `allocated_available` flag, packs paths
/// + claim into CStrings, and hands the box back.
fn finalize_scan_handle(output: crate::FallbackScanOutput) -> *mut ApfsScan {
    let tree = Tree::build(&output.parser_output.entries);
    let mut allocated_available = false;
    for entry in &output.parser_output.entries {
        if entry.allocated_size.is_some() {
            allocated_available = true;
            break;
        }
    }
    let claim_c = CString::new(output.correctness_claim.clone())
        .unwrap_or_else(|_| CString::new("").unwrap());
    let source_kind_c = CString::new(output.parser_output.source.source_kind.clone())
        .unwrap_or_else(|_| CString::new("").unwrap());
    let source_requested_path_c = CString::new(
        output
            .parser_output
            .source
            .requested_path
            .to_string_lossy()
            .into_owned(),
    )
    .unwrap_or_else(|_| CString::new("").unwrap());
    Box::into_raw(Box::new(ApfsScan {
        output,
        tree,
        path_cache: std::sync::Mutex::new(HashMap::new()),
        correctness_claim: claim_c,
        source_kind: source_kind_c,
        source_requested_path: source_requested_path_c,
        allocated_available,
    }))
}

/// Drop a scan handle. Idempotent on NULL.
#[no_mangle]
pub extern "C" fn apfs_scan_free(scan: *mut ApfsScan) {
    ffi_guard((), move || {
        if scan.is_null() {
            return;
        }
        // SAFETY: caller must have obtained `scan` from
        // `apfs_scan_directory` and not yet freed it.
        unsafe {
            drop(Box::from_raw(scan));
        }
    })
}

/// Number of `NamespaceEntry` rows in the scan.
#[no_mangle]
pub extern "C" fn apfs_scan_entry_count(scan: *const ApfsScan) -> u64 {
    ffi_guard(0, move || {
        let Some(s) = (unsafe { scan.as_ref() }) else {
            return 0;
        };
        s.output.parser_output.entries.len() as u64
    })
}

/// Sum of `entry.logical_size` across the whole scan. Reads off
/// the tree root's pre-computed aggregate.
#[no_mangle]
pub extern "C" fn apfs_scan_logical_total(scan: *const ApfsScan) -> u64 {
    ffi_guard(0, move || {
        let Some(s) = (unsafe { scan.as_ref() }) else {
            return 0;
        };
        s.tree.nodes.first().map(|r| r.value_logical).unwrap_or(0)
    })
}

/// Sum of `entry.allocated_size` across the whole scan, or
/// `APFS_ALLOCATED_TOTAL_UNCLAIMED` (`u64::MAX`) when *any* row
/// had `allocated_size = None` (SR-019 None-collapse). Reads off
/// the tree root's pre-computed aggregate.
#[no_mangle]
pub extern "C" fn apfs_scan_allocated_total(scan: *const ApfsScan) -> u64 {
    ffi_guard(APFS_ALLOCATED_TOTAL_UNCLAIMED, move || {
        let Some(s) = (unsafe { scan.as_ref() }) else {
            return APFS_ALLOCATED_TOTAL_UNCLAIMED;
        };
        s.tree
            .nodes
            .first()
            .and_then(|r| r.value_allocated)
            .unwrap_or(APFS_ALLOCATED_TOTAL_UNCLAIMED)
    })
}

// ─────────────────────────────────────────────────────────────
// Phase 3a: tree query FFI
// ─────────────────────────────────────────────────────────────

/// Total number of nodes in the tree (root + every directory +
/// every leaf). Differs from `apfs_scan_entry_count` because the
/// tree also has synthesized intermediate directories.
#[no_mangle]
pub extern "C" fn apfs_scan_node_count(scan: *const ApfsScan) -> u32 {
    ffi_guard(0, move || {
        let Some(s) = (unsafe { scan.as_ref() }) else {
            return 0;
        };
        s.tree.nodes.len() as u32
    })
}

/// Sentinel returned by `apfs_scan_node_index_for_path` (and
/// future phase-3 hit-test FFIs) when no node matches. Matches
/// `crate::tree::NODE_INVALID == u32::MAX`.
pub const APFS_NODE_INVALID: u32 = u32::MAX;

/// Look up a node by its absolute logical path. The empty string
/// (and `"/"`) maps to the synthesised root (index 0). Returns
/// `APFS_NODE_INVALID` if no such node exists.
#[no_mangle]
pub extern "C" fn apfs_scan_node_index_for_path(scan: *const ApfsScan, path: *const c_char) -> u32 {
    ffi_guard(APFS_NODE_INVALID, move || {
        if path.is_null() {
            return APFS_NODE_INVALID;
        }
        let Some(s) = (unsafe { scan.as_ref() }) else {
            return APFS_NODE_INVALID;
        };
        let cstr = unsafe { CStr::from_ptr(path) };
        let p = match cstr.to_str() {
            Ok(p) => p,
            Err(_) => return APFS_NODE_INVALID,
        };
        let idx = s.tree.node_index_for_path(p);
        if idx == NODE_INVALID {
            APFS_NODE_INVALID
        } else {
            idx
        }
    })
}

/// Number of immediate children of the given node.
/// `apfs_scan_node_child_count(s, root) == top-level dir/file
/// count`. Returns 0 for invalid indices.
#[no_mangle]
pub extern "C" fn apfs_scan_node_child_count(scan: *const ApfsScan, idx: u32) -> u32 {
    ffi_guard(0, move || {
        let Some(s) = (unsafe { scan.as_ref() }) else {
            return 0;
        };
        if (idx as usize) >= s.tree.nodes.len() {
            return 0;
        }
        s.tree.nodes[idx as usize].children_count
    })
}

/// Per-node aggregate read by Swift's status bar. Pre-computed
/// post-order at `Tree::build` time; constant-time lookup.
#[no_mangle]
pub extern "C" fn apfs_scan_node_value_logical(scan: *const ApfsScan, idx: u32) -> u64 {
    ffi_guard(0, move || {
        let Some(s) = (unsafe { scan.as_ref() }) else {
            return 0;
        };
        if (idx as usize) >= s.tree.nodes.len() {
            return 0;
        }
        s.tree.nodes[idx as usize].value_logical
    })
}

/// `value_allocated` for the node, or
/// `APFS_ALLOCATED_TOTAL_UNCLAIMED` (`u64::MAX`) when SR-019
/// None-collapse fired anywhere in this subtree.
#[no_mangle]
pub extern "C" fn apfs_scan_node_value_allocated(scan: *const ApfsScan, idx: u32) -> u64 {
    ffi_guard(APFS_ALLOCATED_TOTAL_UNCLAIMED, move || {
        let Some(s) = (unsafe { scan.as_ref() }) else {
            return APFS_ALLOCATED_TOTAL_UNCLAIMED;
        };
        if (idx as usize) >= s.tree.nodes.len() {
            return APFS_ALLOCATED_TOTAL_UNCLAIMED;
        }
        s.tree.nodes[idx as usize]
            .value_allocated
            .unwrap_or(APFS_ALLOCATED_TOTAL_UNCLAIMED)
    })
}

/// Item count for the node — number of non-directory descendants.
/// `apfs_scan_node_item_count(s, root) == files+symlinks total`.
#[no_mangle]
pub extern "C" fn apfs_scan_node_item_count(scan: *const ApfsScan, idx: u32) -> u64 {
    ffi_guard(0, move || {
        let Some(s) = (unsafe { scan.as_ref() }) else {
            return 0;
        };
        if (idx as usize) >= s.tree.nodes.len() {
            return 0;
        }
        s.tree.nodes[idx as usize].item_count
    })
}

/// Borrowed (ptr, len) pair pointing into a `Tree`-owned UTF-8
/// string. Valid for the lifetime of the enclosing `ApfsScan`.
/// `bytes` is *not* NUL-terminated — Swift constructs `String`
/// via `Data(bytes:count:)` + `String(data:encoding:)`.
///
/// We don't pay for CString-style NUL-terminated copies for
/// every node because at /-scale that's ~150 MB of duplicate
/// path storage; the borrowed pointer trades one extra Swift
/// API call for zero allocation.
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ApfsPathRef {
    pub bytes: *const u8,
    pub len: u64,
}

/// Borrow the node's absolute logical path. Returns a null
/// pointer + zero length for invalid indices.
///
/// The path isn't stored on `TreeNode` (round 4 of the perf
/// pass dropped it — saved 16 B per node). We compute on demand
/// via parent-walk and cache the materialised `Box<str>` in
/// `ApfsScan.path_cache`. Pointer lifetime matches the scan
/// handle: the cache owns the bytes until `apfs_scan_free`.
#[no_mangle]
pub extern "C" fn apfs_scan_node_path(scan: *const ApfsScan, idx: u32) -> ApfsPathRef {
    ffi_guard(
        ApfsPathRef {
            bytes: ptr::null(),
            len: 0,
        },
        move || {
            let null_ref = ApfsPathRef {
                bytes: ptr::null(),
                len: 0,
            };
            let Some(s) = (unsafe { scan.as_ref() }) else {
                return null_ref;
            };
            if (idx as usize) >= s.tree.nodes.len() {
                return null_ref;
            }
            let mut cache = s.path_cache.lock().unwrap();
            // The entry stays in the HashMap for the lifetime of
            // `ApfsScan`, so the borrowed slice is valid until
            // `apfs_scan_free`. The `&'static str` lifetime extension
            // below is justified by that invariant; we only hand the
            // pointer + length across the FFI boundary, never a
            // reference Rust has to verify.
            let entry = cache.entry(idx).or_insert_with(|| s.tree.compute_path(idx));
            let bytes = entry.as_ptr();
            let len = entry.len() as u64;
            ApfsPathRef { bytes, len }
        },
    )
}

/// Borrow the node's last path component (display name). Like
/// `apfs_scan_node_path` but returns just the leaf basename.
#[no_mangle]
pub extern "C" fn apfs_scan_node_name(scan: *const ApfsScan, idx: u32) -> ApfsPathRef {
    ffi_guard(
        ApfsPathRef {
            bytes: ptr::null(),
            len: 0,
        },
        move || {
            let null_ref = ApfsPathRef {
                bytes: ptr::null(),
                len: 0,
            };
            let Some(s) = (unsafe { scan.as_ref() }) else {
                return null_ref;
            };
            if (idx as usize) >= s.tree.nodes.len() {
                return null_ref;
            }
            let n = &s.tree.nodes[idx as usize].name;
            ApfsPathRef {
                bytes: n.as_ptr(),
                len: n.len() as u64,
            }
        },
    )
}

/// Parent index for `idx`, or `APFS_NODE_INVALID` for the root
/// (no parent) or an invalid `idx`. Used by Swift's breadcrumb
/// construction (walk parent chain from `currentNode` to root).
#[no_mangle]
pub extern "C" fn apfs_scan_node_parent(scan: *const ApfsScan, idx: u32) -> u32 {
    ffi_guard(APFS_NODE_INVALID, move || {
        let Some(s) = (unsafe { scan.as_ref() }) else {
            return APFS_NODE_INVALID;
        };
        if (idx as usize) >= s.tree.nodes.len() {
            return APFS_NODE_INVALID;
        }
        s.tree.nodes[idx as usize]
            .parent
            .unwrap_or(APFS_NODE_INVALID)
    })
}

/// Returns the node's `EntryKind` as a u32 discriminant:
///   0 = dir, 1 = file, 2 = symlink, 3 = other, 0xff = invalid
/// Swift maps back to a `Scan.NodeKind` enum.
#[no_mangle]
pub extern "C" fn apfs_scan_node_kind(scan: *const ApfsScan, idx: u32) -> u32 {
    ffi_guard(0xff, move || {
        let Some(s) = (unsafe { scan.as_ref() }) else {
            return 0xff;
        };
        if (idx as usize) >= s.tree.nodes.len() {
            return 0xff;
        }
        match s.tree.nodes[idx as usize].kind {
            crate::EntryKind::Dir => 0,
            crate::EntryKind::File => 1,
            crate::EntryKind::Symlink => 2,
            crate::EntryKind::Other => 3,
        }
    })
}

/// Borrowed (ptr, count) slice of child node indices. Lifetime
/// is tied to the enclosing `ApfsScan`; Swift reads as
/// `UnsafeBufferPointer<UInt32>` with no copy.
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ApfsU32Slice {
    pub items: *const u32,
    pub count: u64,
}

/// Borrow the slice of immediate-child node indices for `idx`.
/// Returns an empty slice for invalid indices or leaves.
#[no_mangle]
pub extern "C" fn apfs_scan_node_children(scan: *const ApfsScan, idx: u32) -> ApfsU32Slice {
    ffi_guard(
        ApfsU32Slice {
            items: ptr::null(),
            count: 0,
        },
        move || {
            let null_slice = ApfsU32Slice {
                items: ptr::null(),
                count: 0,
            };
            let Some(s) = (unsafe { scan.as_ref() }) else {
                return null_slice;
            };
            if (idx as usize) >= s.tree.nodes.len() {
                return null_slice;
            }
            let children = s.tree.children_of(idx);
            if children.is_empty() {
                return null_slice;
            }
            ApfsU32Slice {
                items: children.as_ptr(),
                count: children.len() as u64,
            }
        },
    )
}

// ─────────────────────────────────────────────────────────────
// Phase 3b/c: treemap layout — opaque handle + hit-test
// ─────────────────────────────────────────────────────────────

// Re-export the cell record under the C ABI so cbindgen picks
// up the symbol. The actual struct lives in `crate::render`.
pub use crate::render::ApfsCell as ApfsCellRecord;

/// Borrowed view over a laid-out cell array. Valid for the
/// lifetime of the enclosing `ApfsLayout`; Swift reads via
/// `UnsafeBufferPointer<ApfsCell>(start: cells, count: count)`
/// without a copy.
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ApfsCellSlice {
    pub cells: *const ApfsCell,
    pub count: u64,
}

/// Sentinel returned by `apfs_layout_hit_test` when no cell
/// covers the point. Matches `crate::tree::NODE_INVALID`
/// (`u32::MAX`).
pub const APFS_CELL_INVALID: u32 = u32::MAX;

/// Lay out the subtree rooted at `node_idx` inside a viewport of
/// (`width`, `height`) CSS pixels. `max_depth = 0` is the
/// no-truncation sentinel (render every descendant; cull only by
/// `MIN_PIXEL_AREA = 1`).
///
/// `metric`:
///   - `0` → logical
///   - `1` → allocated
///
/// The returned handle owns both the cell array and the
/// `HitGrid` for hit-testing. Always pair with
/// `apfs_layout_free`.
#[no_mangle]
pub extern "C" fn apfs_layout_new(
    scan: *const ApfsScan,
    node_idx: u32,
    max_depth: u32,
    metric: u32,
    width: f32,
    height: f32,
) -> *mut ApfsLayout {
    ffi_guard(ptr::null_mut(), move || {
        let Some(s) = (unsafe { scan.as_ref() }) else {
            return ptr::null_mut();
        };
        let metric_enum = if metric == 1 {
            Metric::Allocated
        } else {
            Metric::Logical
        };
        let cells = render_cells(
            &s.tree,
            node_idx,
            max_depth,
            metric_enum,
            width as f64,
            height as f64,
        );
        if cells.is_empty() {
            return ptr::null_mut();
        }
        let boxed: Box<[ApfsCell]> = cells.into_boxed_slice();
        let hit_grid = HitGrid::build(&boxed, width, height);
        let layout = Box::new(ApfsLayout {
            cells: boxed,
            hit_grid,
        });
        Box::into_raw(layout)
    })
}

/// Reclaim a layout previously returned by `apfs_layout_new`.
/// Idempotent on NULL.
#[no_mangle]
pub extern "C" fn apfs_layout_free(layout: *mut ApfsLayout) {
    ffi_guard((), move || {
        if layout.is_null() {
            return;
        }
        // SAFETY: caller obtained `layout` from `apfs_layout_new`
        // and has not yet freed it. Box drop releases cells +
        // hit_grid in one shot.
        unsafe {
            drop(Box::from_raw(layout));
        }
    })
}

/// Borrow the laid-out cells. Pointer lifetime is tied to the
/// enclosing `ApfsLayout`; Swift must not retain the slice past
/// the layout handle's lifetime.
#[no_mangle]
pub extern "C" fn apfs_layout_cells(layout: *const ApfsLayout) -> ApfsCellSlice {
    ffi_guard(
        ApfsCellSlice {
            cells: ptr::null(),
            count: 0,
        },
        move || {
            let empty = ApfsCellSlice {
                cells: ptr::null(),
                count: 0,
            };
            let Some(l) = (unsafe { layout.as_ref() }) else {
                return empty;
            };
            ApfsCellSlice {
                cells: l.cells.as_ptr(),
                count: l.cells.len() as u64,
            }
        },
    )
}

/// Number of cells in the layout. Convenience accessor — the
/// same value is on `ApfsCellSlice.count`.
#[no_mangle]
pub extern "C" fn apfs_layout_cell_count(layout: *const ApfsLayout) -> u64 {
    ffi_guard(0, move || {
        let Some(l) = (unsafe { layout.as_ref() }) else {
            return 0;
        };
        l.cells.len() as u64
    })
}

/// Find the deepest cell containing `(x, y)`. Returns
/// `APFS_CELL_INVALID` (`u32::MAX`) if no cell does or
/// `(x, y)` is outside the laid-out rect. Sub-millisecond on a
/// /-class scan thanks to the 64×64 spatial hash; OK to call
/// every mousemove.
#[no_mangle]
pub extern "C" fn apfs_layout_hit_test(layout: *const ApfsLayout, x: f32, y: f32) -> u32 {
    ffi_guard(APFS_CELL_INVALID, move || {
        let Some(l) = (unsafe { layout.as_ref() }) else {
            return APFS_CELL_INVALID;
        };
        l.hit_grid
            .hit_test(x, y, &l.cells)
            .unwrap_or(APFS_CELL_INVALID)
    })
}

// ─────────────────────────────────────────────────────────────
// Phase 5d: ext-list summary
// ─────────────────────────────────────────────────────────────

/// Opaque handle holding a `(rows, total_value, any_unclaimed)`
/// snapshot built from a subtree walk. Swift constructs via
/// `apfs_scan_ext_summary_new`, reads rows via `_count` /
/// `_row`, drops via `_free`.
pub struct ApfsExtSummaryHandle(pub(crate) ExtSummary);

/// One ext-list row, flattened for the C ABI. Strings are
/// borrowed (lifetime tied to the enclosing
/// `ApfsExtSummaryHandle`); `value_allocated == u64::MAX` is
/// the SR-019 None-collapse sentinel.
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ApfsExtRow {
    pub ext: ApfsPathRef,
    pub value_logical: u64,
    pub value_allocated: u64,
    pub file_count: u32,
    pub _pad: u32,
}

/// Construct the ext-list summary for the subtree rooted at
/// `node_idx`. `metric == 1` sorts by allocated; anything else
/// sorts by logical. Returns NULL on invalid scan / idx.
#[no_mangle]
pub extern "C" fn apfs_scan_ext_summary_new(
    scan: *const ApfsScan,
    node_idx: u32,
    metric: u32,
) -> *mut ApfsExtSummaryHandle {
    ffi_guard(ptr::null_mut(), move || {
        let Some(s) = (unsafe { scan.as_ref() }) else {
            return ptr::null_mut();
        };
        if (node_idx as usize) >= s.tree.nodes.len() {
            return ptr::null_mut();
        }
        let metric_enum = if metric == 1 {
            Metric::Allocated
        } else {
            Metric::Logical
        };
        let summary = ExtSummary::build(&s.tree, node_idx, metric_enum);
        Box::into_raw(Box::new(ApfsExtSummaryHandle(summary)))
    })
}

/// Drop the summary handle. Idempotent on NULL.
#[no_mangle]
pub extern "C" fn apfs_scan_ext_summary_free(handle: *mut ApfsExtSummaryHandle) {
    ffi_guard((), move || {
        if handle.is_null() {
            return;
        }
        // SAFETY: caller obtained `handle` from `_new` and hasn't
        // freed it.
        unsafe {
            drop(Box::from_raw(handle));
        }
    })
}

#[no_mangle]
pub extern "C" fn apfs_scan_ext_summary_count(handle: *const ApfsExtSummaryHandle) -> u32 {
    ffi_guard(0, move || {
        let Some(h) = (unsafe { handle.as_ref() }) else {
            return 0;
        };
        h.0.rows.len() as u32
    })
}

/// Sum of the active-metric values across all rows. Used by
/// Swift for the per-row percent column. Returns 0 on
/// invalid handle.
#[no_mangle]
pub extern "C" fn apfs_scan_ext_summary_total(handle: *const ApfsExtSummaryHandle) -> u64 {
    ffi_guard(0, move || {
        let Some(h) = (unsafe { handle.as_ref() }) else {
            return 0;
        };
        h.0.total_value
    })
}

/// True iff at least one contributing file's `allocated_size`
/// was None (SR-019 None-collapse). The Swift panel uses this
/// to caption the header subtitle.
#[no_mangle]
pub extern "C" fn apfs_scan_ext_summary_any_unclaimed(handle: *const ApfsExtSummaryHandle) -> bool {
    ffi_guard(false, move || {
        let Some(h) = (unsafe { handle.as_ref() }) else {
            return false;
        };
        h.0.any_unclaimed
    })
}

/// Fetch row `n`. Returns a zero-filled row if `n` is out of
/// range or the handle is NULL.
#[no_mangle]
pub extern "C" fn apfs_scan_ext_summary_row(
    handle: *const ApfsExtSummaryHandle,
    n: u32,
) -> ApfsExtRow {
    ffi_guard(
        ApfsExtRow {
            ext: ApfsPathRef {
                bytes: ptr::null(),
                len: 0,
            },
            value_logical: 0,
            value_allocated: APFS_ALLOCATED_TOTAL_UNCLAIMED,
            file_count: 0,
            _pad: 0,
        },
        move || {
            let zero = ApfsExtRow {
                ext: ApfsPathRef {
                    bytes: ptr::null(),
                    len: 0,
                },
                value_logical: 0,
                value_allocated: APFS_ALLOCATED_TOTAL_UNCLAIMED,
                file_count: 0,
                _pad: 0,
            };
            let Some(h) = (unsafe { handle.as_ref() }) else {
                return zero;
            };
            let idx = n as usize;
            if idx >= h.0.rows.len() {
                return zero;
            }
            let row = &h.0.rows[idx];
            let allocated = row
                .value_allocated
                .unwrap_or(APFS_ALLOCATED_TOTAL_UNCLAIMED);
            ApfsExtRow {
                ext: ApfsPathRef {
                    bytes: row.ext.as_ptr(),
                    len: row.ext.len() as u64,
                },
                value_logical: row.value_logical,
                value_allocated: allocated,
                file_count: row.file_count,
                _pad: 0,
            }
        },
    )
}

/// `true` iff at least one entry has `allocated_size = Some(_)`.
/// The Swift UI uses this to gate the "Allocated" metric chip.
#[no_mangle]
pub extern "C" fn apfs_scan_allocated_available(scan: *const ApfsScan) -> bool {
    ffi_guard(false, move || {
        let Some(s) = (unsafe { scan.as_ref() }) else {
            return false;
        };
        s.allocated_available
    })
}

/// `correctness_claim` (UTF-8, NUL-terminated). The returned
/// pointer is owned by `scan` and is valid until
/// `apfs_scan_free(scan)`. Swift must not free it.
#[no_mangle]
pub extern "C" fn apfs_scan_correctness_claim(scan: *const ApfsScan) -> *const c_char {
    ffi_guard(ptr::null(), move || {
        let Some(s) = (unsafe { scan.as_ref() }) else {
            return ptr::null();
        };
        s.correctness_claim.as_ptr()
    })
}

/// `SourceDescriptor.source_kind` (e.g. `"mounted_directory"`,
/// `"dmg_image"`). UTF-8, NUL-terminated; owned by `scan`.
#[no_mangle]
pub extern "C" fn apfs_scan_source_kind(scan: *const ApfsScan) -> *const c_char {
    ffi_guard(ptr::null(), move || {
        let Some(s) = (unsafe { scan.as_ref() }) else {
            return ptr::null();
        };
        s.source_kind.as_ptr()
    })
}

/// `SourceDescriptor.requested_path`, the absolute path the user
/// asked us to scan. UTF-8, NUL-terminated; owned by `scan`.
#[no_mangle]
pub extern "C" fn apfs_scan_source_requested_path(scan: *const ApfsScan) -> *const c_char {
    ffi_guard(ptr::null(), move || {
        let Some(s) = (unsafe { scan.as_ref() }) else {
            return ptr::null();
        };
        s.source_requested_path.as_ptr()
    })
}
