//! C ABI surface consumed by the native renderer's Swift code.
//!
//! Everything that crosses this boundary is `#[no_mangle] extern
//! "C"`. The header is generated by cbindgen at build time
//! (`build.rs`), then `build-native.sh` copies it into the
//! SwiftPM `CApfsFastindex` shim target.
//!
//! Design notes:
//!
//! - Strings cross the boundary as `*const c_char` (UTF-8,
//!   NUL-terminated). Swift wraps with `String(cString:)`. The
//!   Rust side owns each string for the lifetime of the
//!   enclosing handle (e.g. an `ApfsScan*` keeps all its path
//!   strings alive until `apfs_scan_free` runs).
//! - Bulk buffers (entry lists, cell lists, tree-list rows) are
//!   exposed as `(*const Item, usize)` pairs so Swift reads
//!   them as `UnsafeBufferPointer` without per-item FFI traffic.
//! - Every "new" function has a matching `_free` that the Swift
//!   side calls in `deinit`. Ownership rule: the caller of `new`
//!   is responsible for `_free`.
//! - Optional integer fields use the sentinel `u64::MAX` (or
//!   `i64::MIN` where applicable) for `None`. Cleaner than a
//!   parallel "has-this-field" bool from a FFI standpoint;
//!   Swift maps the sentinel back to `nil` on the wrapper side.

use std::ffi::{CStr, CString};
use std::os::raw::{c_char, c_int};
use std::ptr;

use crate::render::{render_cells, ApfsCell, Metric};
use crate::tree::{Tree, NODE_INVALID};
use crate::{fallback_scan_path_with_options, FallbackOptions};

// ─────────────────────────────────────────────────────────────
// Phase 1 sanity-check surface
// ─────────────────────────────────────────────────────────────

/// Returns a constant integer the Swift side can assert on to
/// confirm the FFI bridge is wired correctly. The number is the
/// MWP-trivia answer; if it changes, something has gone wrong
/// with name mangling or the static-lib search path.
#[no_mangle]
pub extern "C" fn apfs_hello() -> c_int {
    42
}

/// Returns the apfs-fastindex crate version as a NUL-terminated
/// UTF-8 string (static, so the pointer is valid for the
/// lifetime of the process — Swift must not free it). The
/// version is baked at compile time from `Cargo.toml`.
#[no_mangle]
pub extern "C" fn apfs_version() -> *const c_char {
    // `concat!` produces a static `&'static str`; appending a
    // trailing `\0` byte and exposing the data pointer is the
    // idiomatic way to hand a C string out of Rust without an
    // allocation.
    static VERSION: &str = concat!(env!("CARGO_PKG_VERSION"), "\0");
    VERSION.as_ptr() as *const c_char
}

// ─────────────────────────────────────────────────────────────
// Phase 2: scan FFI
// ─────────────────────────────────────────────────────────────

/// Opaque handle representing a completed fallback scan. Owns
/// the entry buffer, the indexed tree, and supporting strings.
/// Swift sees a `*mut ApfsScan` and must call `apfs_scan_free`
/// when done.
pub struct ApfsScan {
    pub(crate) output: crate::FallbackScanOutput,
    /// Indexed tree over `output.parser_output.entries`.
    /// Phase 3 builds this at scan time so the renderer can
    /// query it by path without re-scanning the entry list.
    pub(crate) tree: Tree,
    // CStrings keep the NUL-terminated bytes alive for the
    // lifetime of the scan. Pointers handed to Swift point
    // into these — Swift must not free them; they go away
    // when `apfs_scan_free` drops the box.
    correctness_claim: CString,
    source_kind: CString,
    source_requested_path: CString,
    /// True iff *any* entry has `allocated_size = Some(_)`.
    /// The Swift UI toggles the "Allocated" metric chip off
    /// when this is false.
    allocated_available: bool,
}

/// Sentinel for "no allocated total" (SR-019 None-collapse).
/// Pre-baked at the C-ABI boundary because Option<u64> doesn't
/// cross unmodified.
const APFS_ALLOCATED_TOTAL_UNCLAIMED: u64 = u64::MAX;

/// Scan a directory and return an owning `ApfsScan*`. `threads`
/// of 0 uses the default (min of physical-cpu and 4 per EX-25).
/// `cross_mounts` toggles whether the walker descends into
/// directories on a different device than the root.
///
/// Returns `NULL` on:
///   - `path` is NULL
///   - `path` is not valid UTF-8
///   - the scan returns an error (bad source, permission denial
///     at root, etc.)
#[no_mangle]
pub extern "C" fn apfs_scan_directory(
    path: *const c_char,
    threads: u32,
    cross_mounts: bool,
) -> *mut ApfsScan {
    if path.is_null() {
        return ptr::null_mut();
    }
    let cstr = unsafe { CStr::from_ptr(path) };
    let path_str = match cstr.to_str() {
        Ok(s) => s,
        Err(_) => return ptr::null_mut(),
    };
    let options = FallbackOptions {
        cross_mounts,
        progress: None,
        threads: if threads == 0 { 4 } else { threads as usize },
    };
    let output = match fallback_scan_path_with_options(path_str, options) {
        Ok(o) => o,
        Err(_) => return ptr::null_mut(),
    };

    // Build the indexed tree. `Tree::build` walks the entries
    // and aggregates value_logical / value_allocated /
    // item_count up the tree in one post-order pass — the root's
    // aggregates are the totals Swift used to read off the cached
    // `logical_total` / `allocated_total` fields, so those are
    // gone now.
    let tree = Tree::build(&output.parser_output.entries);

    // The "allocated-available" flag is still cheap to compute
    // off the flat entry list; doing so during tree-build would
    // mean a second branch in the hot loop.
    let mut allocated_available = false;
    for entry in &output.parser_output.entries {
        if entry.allocated_size.is_some() {
            allocated_available = true;
            break;
        }
    }

    let claim_c = CString::new(output.correctness_claim.clone())
        .unwrap_or_else(|_| CString::new("").unwrap());
    let source_kind_c = CString::new(output.parser_output.source.source_kind.clone())
        .unwrap_or_else(|_| CString::new("").unwrap());
    let source_requested_path_c = CString::new(
        output.parser_output.source.requested_path.to_string_lossy().into_owned(),
    )
    .unwrap_or_else(|_| CString::new("").unwrap());

    let scan = Box::new(ApfsScan {
        output,
        tree,
        correctness_claim: claim_c,
        source_kind: source_kind_c,
        source_requested_path: source_requested_path_c,
        allocated_available,
    });
    Box::into_raw(scan)
}

/// Drop a scan handle. Idempotent on NULL.
#[no_mangle]
pub extern "C" fn apfs_scan_free(scan: *mut ApfsScan) {
    if scan.is_null() {
        return;
    }
    // SAFETY: caller must have obtained `scan` from
    // `apfs_scan_directory` and not yet freed it.
    unsafe {
        drop(Box::from_raw(scan));
    }
}

/// Number of `NamespaceEntry` rows in the scan.
#[no_mangle]
pub extern "C" fn apfs_scan_entry_count(scan: *const ApfsScan) -> u64 {
    let Some(s) = (unsafe { scan.as_ref() }) else { return 0; };
    s.output.parser_output.entries.len() as u64
}

/// Sum of `entry.logical_size` across the whole scan. Reads off
/// the tree root's pre-computed aggregate.
#[no_mangle]
pub extern "C" fn apfs_scan_logical_total(scan: *const ApfsScan) -> u64 {
    let Some(s) = (unsafe { scan.as_ref() }) else { return 0; };
    s.tree.nodes.first().map(|r| r.value_logical).unwrap_or(0)
}

/// Sum of `entry.allocated_size` across the whole scan, or
/// `APFS_ALLOCATED_TOTAL_UNCLAIMED` (`u64::MAX`) when *any* row
/// had `allocated_size = None` (SR-019 None-collapse). Reads off
/// the tree root's pre-computed aggregate.
#[no_mangle]
pub extern "C" fn apfs_scan_allocated_total(scan: *const ApfsScan) -> u64 {
    let Some(s) = (unsafe { scan.as_ref() }) else { return APFS_ALLOCATED_TOTAL_UNCLAIMED; };
    s.tree
        .nodes
        .first()
        .and_then(|r| r.value_allocated)
        .unwrap_or(APFS_ALLOCATED_TOTAL_UNCLAIMED)
}

// ─────────────────────────────────────────────────────────────
// Phase 3a: tree query FFI
// ─────────────────────────────────────────────────────────────

/// Total number of nodes in the tree (root + every directory +
/// every leaf). Differs from `apfs_scan_entry_count` because the
/// tree also has synthesized intermediate directories.
#[no_mangle]
pub extern "C" fn apfs_scan_node_count(scan: *const ApfsScan) -> u32 {
    let Some(s) = (unsafe { scan.as_ref() }) else { return 0; };
    s.tree.nodes.len() as u32
}

/// Sentinel returned by `apfs_scan_node_index_for_path` (and
/// future phase-3 hit-test FFIs) when no node matches. Matches
/// `crate::tree::NODE_INVALID == u32::MAX`.
pub const APFS_NODE_INVALID: u32 = u32::MAX;

/// Look up a node by its absolute logical path. The empty string
/// (and `"/"`) maps to the synthesised root (index 0). Returns
/// `APFS_NODE_INVALID` if no such node exists.
#[no_mangle]
pub extern "C" fn apfs_scan_node_index_for_path(
    scan: *const ApfsScan,
    path: *const c_char,
) -> u32 {
    if path.is_null() {
        return APFS_NODE_INVALID;
    }
    let Some(s) = (unsafe { scan.as_ref() }) else { return APFS_NODE_INVALID; };
    let cstr = unsafe { CStr::from_ptr(path) };
    let p = match cstr.to_str() {
        Ok(p) => p,
        Err(_) => return APFS_NODE_INVALID,
    };
    let idx = s.tree.node_index_for_path(p);
    if idx == NODE_INVALID {
        APFS_NODE_INVALID
    } else {
        idx
    }
}

/// Number of immediate children of the given node.
/// `apfs_scan_node_child_count(s, root) == top-level dir/file
/// count`. Returns 0 for invalid indices.
#[no_mangle]
pub extern "C" fn apfs_scan_node_child_count(scan: *const ApfsScan, idx: u32) -> u32 {
    let Some(s) = (unsafe { scan.as_ref() }) else { return 0; };
    if (idx as usize) >= s.tree.nodes.len() {
        return 0;
    }
    s.tree.nodes[idx as usize].children.len() as u32
}

/// Per-node aggregate read by Swift's status bar. Pre-computed
/// post-order at `Tree::build` time; constant-time lookup.
#[no_mangle]
pub extern "C" fn apfs_scan_node_value_logical(scan: *const ApfsScan, idx: u32) -> u64 {
    let Some(s) = (unsafe { scan.as_ref() }) else { return 0; };
    if (idx as usize) >= s.tree.nodes.len() {
        return 0;
    }
    s.tree.nodes[idx as usize].value_logical
}

/// `value_allocated` for the node, or
/// `APFS_ALLOCATED_TOTAL_UNCLAIMED` (`u64::MAX`) when SR-019
/// None-collapse fired anywhere in this subtree.
#[no_mangle]
pub extern "C" fn apfs_scan_node_value_allocated(scan: *const ApfsScan, idx: u32) -> u64 {
    let Some(s) = (unsafe { scan.as_ref() }) else { return APFS_ALLOCATED_TOTAL_UNCLAIMED; };
    if (idx as usize) >= s.tree.nodes.len() {
        return APFS_ALLOCATED_TOTAL_UNCLAIMED;
    }
    s.tree.nodes[idx as usize]
        .value_allocated
        .unwrap_or(APFS_ALLOCATED_TOTAL_UNCLAIMED)
}

/// Item count for the node — number of non-directory descendants.
/// `apfs_scan_node_item_count(s, root) == files+symlinks total`.
#[no_mangle]
pub extern "C" fn apfs_scan_node_item_count(scan: *const ApfsScan, idx: u32) -> u64 {
    let Some(s) = (unsafe { scan.as_ref() }) else { return 0; };
    if (idx as usize) >= s.tree.nodes.len() {
        return 0;
    }
    s.tree.nodes[idx as usize].item_count
}

/// Borrowed (ptr, len) pair pointing into a `Tree`-owned UTF-8
/// string. Valid for the lifetime of the enclosing `ApfsScan`.
/// `bytes` is *not* NUL-terminated — Swift constructs `String`
/// via `Data(bytes:count:)` + `String(data:encoding:)`.
///
/// We don't pay for CString-style NUL-terminated copies for
/// every node because at /-scale that's ~150 MB of duplicate
/// path storage; the borrowed pointer trades one extra Swift
/// API call for zero allocation.
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ApfsPathRef {
    pub bytes: *const u8,
    pub len: u64,
}

/// Borrow the node's absolute logical path. Returns a null
/// pointer + zero length for invalid indices.
#[no_mangle]
pub extern "C" fn apfs_scan_node_path(scan: *const ApfsScan, idx: u32) -> ApfsPathRef {
    let null_ref = ApfsPathRef { bytes: ptr::null(), len: 0 };
    let Some(s) = (unsafe { scan.as_ref() }) else { return null_ref; };
    if (idx as usize) >= s.tree.nodes.len() {
        return null_ref;
    }
    let p = &s.tree.nodes[idx as usize].path;
    ApfsPathRef { bytes: p.as_ptr(), len: p.len() as u64 }
}

/// Borrow the node's last path component (display name). Like
/// `apfs_scan_node_path` but returns just the leaf basename.
#[no_mangle]
pub extern "C" fn apfs_scan_node_name(scan: *const ApfsScan, idx: u32) -> ApfsPathRef {
    let null_ref = ApfsPathRef { bytes: ptr::null(), len: 0 };
    let Some(s) = (unsafe { scan.as_ref() }) else { return null_ref; };
    if (idx as usize) >= s.tree.nodes.len() {
        return null_ref;
    }
    let n = &s.tree.nodes[idx as usize].name;
    ApfsPathRef { bytes: n.as_ptr(), len: n.len() as u64 }
}

// ─────────────────────────────────────────────────────────────
// Phase 3b: treemap render — laid-out cell slice
// ─────────────────────────────────────────────────────────────

// Re-export the cell record under the C ABI so cbindgen picks
// up the symbol. The actual struct lives in `crate::render`.
pub use crate::render::ApfsCell as ApfsCellRecord;

/// Borrowed slice of laid-out cells. Lifetime is tied to the
/// `ApfsCellSlice` itself — the underlying `Box<[ApfsCell]>` is
/// reclaimed when Swift calls `apfs_render_cells_free` with
/// this slice. Swift reads via
/// `UnsafeBufferPointer<ApfsCellRecord>(start: cells, count: count)`.
#[repr(C)]
#[derive(Copy, Clone)]
pub struct ApfsCellSlice {
    pub cells: *const ApfsCell,
    pub count: u64,
}

/// Lay out the subtree rooted at `node_idx` inside a viewport of
/// (`width`, `height`) CSS pixels. `max_depth = 0` is the
/// no-truncation sentinel (matches the JS depth picker — render
/// every descendant, cull only by min pixel area).
///
/// `metric`:
///   - `0` → logical
///   - `1` → allocated
///
/// The returned slice owns its memory. Pair every successful
/// call with `apfs_render_cells_free(slice)` once the Swift
/// renderer has drawn from it.
#[no_mangle]
pub extern "C" fn apfs_render_cells(
    scan: *const ApfsScan,
    node_idx: u32,
    max_depth: u32,
    metric: u32,
    width: f32,
    height: f32,
) -> ApfsCellSlice {
    let empty = ApfsCellSlice { cells: ptr::null(), count: 0 };
    let Some(s) = (unsafe { scan.as_ref() }) else { return empty; };
    let metric_enum = if metric == 1 { Metric::Allocated } else { Metric::Logical };
    let cells = render_cells(
        &s.tree,
        node_idx,
        max_depth,
        metric_enum,
        width as f64,
        height as f64,
    );
    if cells.is_empty() {
        return empty;
    }
    // Move the Vec into a fixed-size boxed slice so the pointer
    // stays stable while Swift reads it. Free path reconstructs
    // the box from `(cells, count)`.
    let boxed: Box<[ApfsCell]> = cells.into_boxed_slice();
    let count = boxed.len() as u64;
    let ptr = Box::into_raw(boxed) as *mut ApfsCell;
    ApfsCellSlice { cells: ptr, count }
}

/// Reclaim a slice previously returned by `apfs_render_cells`.
/// Idempotent on NULL.
#[no_mangle]
pub extern "C" fn apfs_render_cells_free(slice: ApfsCellSlice) {
    if slice.cells.is_null() || slice.count == 0 {
        return;
    }
    // SAFETY: `cells` came from `Box::into_raw` over a slice
    // of length `count`; reconstruct + drop.
    unsafe {
        drop(Box::from_raw(std::slice::from_raw_parts_mut(
            slice.cells as *mut ApfsCell,
            slice.count as usize,
        )));
    }
}

/// `true` iff at least one entry has `allocated_size = Some(_)`.
/// The Swift UI uses this to gate the "Allocated" metric chip.
#[no_mangle]
pub extern "C" fn apfs_scan_allocated_available(scan: *const ApfsScan) -> bool {
    let Some(s) = (unsafe { scan.as_ref() }) else { return false; };
    s.allocated_available
}

/// `correctness_claim` (UTF-8, NUL-terminated). The returned
/// pointer is owned by `scan` and is valid until
/// `apfs_scan_free(scan)`. Swift must not free it.
#[no_mangle]
pub extern "C" fn apfs_scan_correctness_claim(scan: *const ApfsScan) -> *const c_char {
    let Some(s) = (unsafe { scan.as_ref() }) else { return ptr::null(); };
    s.correctness_claim.as_ptr()
}

/// `SourceDescriptor.source_kind` (e.g. `"mounted_directory"`,
/// `"dmg_image"`). UTF-8, NUL-terminated; owned by `scan`.
#[no_mangle]
pub extern "C" fn apfs_scan_source_kind(scan: *const ApfsScan) -> *const c_char {
    let Some(s) = (unsafe { scan.as_ref() }) else { return ptr::null(); };
    s.source_kind.as_ptr()
}

/// `SourceDescriptor.requested_path`, the absolute path the user
/// asked us to scan. UTF-8, NUL-terminated; owned by `scan`.
#[no_mangle]
pub extern "C" fn apfs_scan_source_requested_path(scan: *const ApfsScan) -> *const c_char {
    let Some(s) = (unsafe { scan.as_ref() }) else { return ptr::null(); };
    s.source_requested_path.as_ptr()
}
